# -*- coding: utf-8 -*-
"""T2-BigData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRVCPVcGA-WlDANB_Uh9bVxYYPMPqxgh
"""

!pip install pyspark

#import findspark
#findspark.init()
from google.colab import drive
import zipfile
from pyspark.sql import SparkSession
spark=SparkSession.builder.appName('Basics').getOrCreate()
import os
drive.mount('/content/drive', force_remount=True)
print(os.listdir("/content/drive/MyDrive/T2-BigData"))
#with zipfile.ZipFile("/content/drive/MyDrive/T2-BigData/crossref.zip", 'r') as zip_ref:
 #   zip_ref.extractall("/content/drive/MyDrive/T2-BigData/crossref")

!cp /content/drive/MyDrive/T2-BigData/crossref.zip /content/
!unzip /content/crossref.zip
files=os.listdir("/content/drive/MyDrive/T2-BigData/crossref")
df=spark.read.option("multiline", "true").json("/content/crossref")

df.printSchema()
df.count()

from pyspark.sql.functions import col, lit, explode
df_transformacion=df.select(
    col("message.DOI").alias("doi"),
    col("message.author").alias("author"),
    col("message.institution").alias("inst"),
    col("message.group-title").alias("groupTitle"),
    col("message.created.date-time").alias("createdDate"),
    col("message.prefix").alias("prefix"),
    col("message.reference").alias("reference"),
    col("message.link").alias("link"),
    col("message.subtype").alias("subtype")
)

df_transformacion.printSchema()

df_transformacion.write.mode("overwrite").parquet("/content/drive/MyDrive/T2-BigData/parquet")

from pyspark.sql.functions import col, year, month, count
df_parquet=spark.read.parquet("/content/drive/MyDrive/T2-BigData/parquet")
df_parquet.printSchema()
df_year_month=df_parquet.withColumn("created_year",year(col("createdDate"))).withColumn("created_month",month(col("createdDate")))
df_year_month_grouped=df_year_month.groupBy("created_year","created_month")
df_dates=df_year_month_grouped.agg(count("created_year").alias("total_articles"))
df_dates.show()
df.count()
#df_dates.write.mode("overwrite").csv("/content/drive/MyDrive/T2-BigData/output/articles_month_year/")